dist: trusty
sudo: require
language: cpp
compiler: g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - cmake
      - libgoogle-glog-dev
      - libgflags-dev
      - libboost-system-dev
      - libboost-timer-dev
      - protobuf-c-compiler
      - protobuf-compiler
      - libprotobuf*
      - lcov
      - uuid-dev
      - libtool
      - libboost-all-dev
      - libevent-dev
      - libdouble-conversion-dev
      - libgoogle-glog-dev
      - libgflags-dev
      - liblz4-dev
      - liblzma-dev
      - libsnappy-dev
      - make
      - zlib1g-dev
      - binutils-dev
      - libjemalloc-dev
      - libssl-dev
      - pkg-config
      - libunwind8-dev
      - libelf-dev
      - libdwarf-dev

before_install:
  - export CXX=g++-6
  - export CC=gcc-6
  - git clone https://github.com/facebook/folly
  - cd folly/folly
  - autoreconf -ivf
  - ./configure
  - make
  - make check
  - sudo make install
  - cd -
  - git clone https://github.com/antlr/antlr4
  - mkdir -p antlr4/runtime/Cpp/build
  - cd antlr4/runtime/Cpp/build
  - cmake -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_BUILD_TYPE=Release ..
  - make -j 2
  - sudo make install
  - cd -

script:
  - git submodule update --init --recursive
  - mkdir -p build && cd build
#  - find . -name "*.gcov" -or -name "*.gcda" -or -name "*.gcno" -exec rm {} \;
#  - rm -fr gcov-html
  - cmake -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_C_COMPILER=gcc-6 ..
  - make -j4
  - GLOG_minloglevel=2 ./test_base_exception
  - GLOG_minloglevel=2 ./test_base_infrastructure
  - GLOG_minloglevel=2 ./test_base_memory
  - GLOG_minloglevel=2 ./test_cursor_base
  - GLOG_minloglevel=2 ./test_cursor_core
  - GLOG_minloglevel=2 ./test_cursor_infrastructure
  - GLOG_minloglevel=2 ./test_expression_core
  - GLOG_minloglevel=2 ./test_expression_infrastructure
  - GLOG_minloglevel=2 ./test_expression_templated
  - GLOG_minloglevel=2 ./test_expression_vector
  - GLOG_minloglevel=2 ./supersonicTest
  - GLOG_minloglevel=2 ./quicksaveTest
#  - find . -name "*.gc*" -exec gcov {} \;
#  - lcov -c -d . -o cov.info
#  - genhtml cov.info --output-directory gcov-html
