dist: trusty
sudo: require
language: cpp
compiler: g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
      - cmake
      - libgoogle-glog-dev
      - libgflags-dev
      - libboost-system-dev
      - libboost-timer-dev
      - protobuf-c-compiler
      - protobuf-compiler
      - libprotobuf*
      - lcov
before_install:
#  - sudo add-apt-repository main -y
#  - sudo add-apt-repository universe -y
#  - sudo add-apt-repository restricted -y
#  - sudo add-apt-repository multiverse -y
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get update -q
#  - sudo apt-cache search protobuf
#  - sudo apt-cache search g++
#  - sudo apt-cache search gcc
  - cd $TRAVIS_BUILD_DIR
script:
  - git submodule update --init --recursive
  - mkdir -p build && cd build
#  - find . -name "*.gcov" -or -name "*.gcda" -or -name "*.gcno" -exec rm {} \;
#  - rm -fr gcov-html
  - cmake -DCMAKE_CXX_COMPILER=g++-6 -DCMAKE_C_COMPILER=gcc-6 ..
  - make -j4
  - GLOG_minloglevel=2 ./test_base_exception
  - GLOG_minloglevel=2 ./test_base_infrastructure
  - GLOG_minloglevel=2 ./test_base_memory
  - GLOG_minloglevel=2 ./test_cursor_base
  - GLOG_minloglevel=2 ./test_cursor_core
  - GLOG_minloglevel=2 ./test_cursor_infrastructure
  - GLOG_minloglevel=2 ./test_expression_core
  - GLOG_minloglevel=2 ./test_expression_infrastructure
  - GLOG_minloglevel=2 ./test_expression_templated
  - GLOG_minloglevel=2 ./test_expression_vector
  - GLOG_minloglevel=2 ./supersonicTest
#  - find . -name "*.gc*" -exec gcov {} \;
#  - lcov -c -d . -o cov.info
#  - genhtml cov.info --output-directory gcov-html
