FROM ubuntu

COPY . /source
COPY docker.sudo /usr/bin/sudo

RUN apt-get update \
    && /source/deps.sh \
    && mkdir -p /source/deps \
    && git clone https://github.com/google/googletest /source/deps/googletest \
    && mkdir -p /build && cd /build && cmake ../source && make

CMD /build/supersonic
