FROM quicksave/dev-python

RUN git clone --recursive https://github.com/adiog/supersonic \
    && cd supersonic \
    && git checkout quicksave \
    && mkdir -p build \
    && cd build \
    && cmake -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_BUILD_TYPE=Release .. \
    && make -j 4

CMD bash

